name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"


        ğŸ‘‹ Hi, Iâ€™m @gopualakrishna6 My Name is Gopu Alakrishna Nagarajan
ğŸ‘€ Iâ€™m interested in ...Helping People affected by Natuaral Disasters, Wars in all Countries
ğŸŒ± Iâ€™m currently learning ...How to help Humans in this world? How to create a safe and peaceful world without Wars?
ğŸ’ï¸ Iâ€™m looking to collaborate on ...Fund raising Helping People affected by Natuaral Disasters, Wars in all Countries
ğŸ“« How to reach me ... gopualakrishna6@yahoo.com Email ID
+91-99005055351 Whatsapp and Mobile Number
Fund can be sent by using my Google Pay using following UPI IDs:

gopualakrishna-2@okhdfcbank / gopualakrishna-1@okaxis / gopualakrishna-2@oksbi

Paypal account details to transfer fund: @gopualakrishna
gopualakrishna@gmail.com paypal registered email
9900505351 paypal registered mobile number

.

I am a Global Peace Maker, Global Citizen, so Could you please send fund generously to my Bit Coin address given below

Send Fund to my BitCoin Address: 1AiRoneVpLjM92BDf4puKXYgX1TcdvqYxi

UPI Money transfer through Paytm address to send fund 9900505351@paytm
